name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint with Ruff
      uses: astral-sh/ruff-action@v1
    - name: Format with Ruff
      uses: astral-sh/ruff-action@v1
      with:
        args: 'format --check'

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Check package build
      run: |
        uv build
